spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Donor
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123456
  jpa:
    generate-ddl: true
    properties:
      hibernate.ddl-auto: CREATE
      jpa.show-sql: true
